 export const actionType ={
    ADD_CATEGOTY :"ADD_CATEGORY",
DELETE_CATEGORY:"DELETE_CATEGORY",
UPDATE_CATEGORY:"UPDATE_CATEGORY",
     SEARCH_CATEGORY: "SEARCH_CATEGORY",
LIST_CATEGORIES:"LIST_CATEGPRIEES"
}