 export const actionType ={
    ADD_CATEGOTY :"ADD_CATEGORY",
DELETE_CATEGORY:"DELETE_CATEGORY",
UPDATE_CATEGORY:"UPDATE_CATEGORY",
     SEARCH_CATEGORY: "SEARCH_CATEGORY",
LIST_CATEGORIES:"LIST_CATEGPRIEES"
}
export const brandConstants ={
     ADD_BRAND :"ADD_BRAND",
     DELETE_BRAND:"DELETE_BRAND",
     UPDATE_BRAND:"UPDATE_BRAND",
          SEARCH_BRAND: "SEARCH_BRAND",
     LIST_BRANDS:"LIST_BRANDS" 
}
export const companyConstants ={
     ADD_COMPANY :"ADD_COMPANY",
     DELETE_COMPANY:"DELETE_COMPANY",
     UPDATE_COMPANY:"UPDATE_COMPANY",
          SEARCH_COMPANY: "SEARCH_COMAPNY",
     LIST_COMPANY:"LIST_COMPANY" 
}
export const storeConstants = {
     ADD_STORE :"ADD_STORE",
     DELETE_STORE:"DELETE_STORE",
     UPDATE_STORE:"UPDATE_STORE",
          SEARCH_STORE: "SEARCH_STORE",
     LIST_STORE: "LIST_STORE", 
    
    
     
}
