 export const actionType ={
    ADD_CATEGOTY :"ADD_CATEGORY",
DELETE_CATEGORY:"DELETE_CATEGORY",
UPDATE_CATEGORY:"UPDATE_CATEGORY",
     SEARCH_CATEGORY: "SEARCH_CATEGORY",
LIST_CATEGORIES:"LIST_CATEGPRIEES"
}
export const brandConstants ={
     ADD_BRAND :"ADD_BRAND",
     DELETE_BRAND:"DELETE_BRAND",
     UPDATE_BRAND:"UPDATE_BRAND",
          SEARCH_BRAND: "SEARCH_BRAND",
     LIST_BRANDS:"LIST_BRANDS" 
}
export const companyConstants ={
     ADD_COMPANY :"ADD_COMPANY",
     DELETE_COMPANY:"DELETE_COMPANY",
     UPDATE_COMPANY:"UPDATE_COMPANY",
          SEARCH_COMPANY: "SEARCH_COMAPNY",
     LIST_COMPANY:"LIST_COMPANY" 
}
export const storeConstants = {
     ADD_STORE :"ADD_STORE",
     DELETE_STORE:"DELETE_STORE",
     UPDATE_STORE:"UPDATE_STORE",
          SEARCH_STORE: "SEARCH_STORE",
     LIST_STORE: "LIST_STORE", 
    
}
export const supplierConstants = {
     ADD_SUPPLIER :"ADD_SUPPLIER",
     DELETE_SUPPLIER:"DELETE_SUPPLIER",
     UPDATE_SUPPLIER:"UPDATE_SUPPLIER",
     SEARCH_SUPPLIER: "SEARCH_SUPPLIER",
     LIST_SUPPLIER: "LIST_SUPPLIER", 
     APROVE_SUPPLIER:"APPROVE_SUPPLIER",
     DECLINE_SUPPLIER:"DECLINE_SUPPLIER"
     
}
export const orderConstants = {
     ADD_ORDER :"ADD_ORDER",
     DELETE_ORDER:"DELETE_ORDER",
     UPDATE_ORDER:"UPDATE_ORDER",
     SEARCH_ORDER:"SEARCH_ORDER",
     LIST_ORDER: "LIST_ORDER", 
   
}
export const productConstants = {
     ADD_PRODUCT :"ADD_PRODUCT",
     DELETE_PRODUCT:"DELETE_PRODUCT",
     UPDATE_PRODUCT:"UPDATE_PRODUCT",
     SEARCH_PRODUCT:"SEARCH_PRODUCT",
     LIST_PRODUCT: "LIST_PRODUCT", 
}
export const inventoryConstants = {
     ADD_INVENTORY :"ADD_INVENTORY",
     DELETE_INVENTORY:"DELETE_INVENTORY",
     UPDATE_INVENTORY:"UPDATE_INVENTORY",
     SEARCH_INVENTORY:"SEARCH_INVENTORY",
     LIST_INVENTORY: "LIST_INVENTORY", 
}
export const userConstants = {
     ADD_USER:"ADD_USER",
     DELETE_USER:"DELETE_USER",
     UPDATE_USER:"UPDATE_USER",
     SEARCH_USER:"SEARCH_USER",
     LIST_USERS: "LIST_USERS", 
     CHECK_TOKEN_SUCESS:'CHECK_TOKEN_SUCESS'
}
export const roleConstants = {
     ADD_ROLE:"ADD_ROLE",
     DELETE_ROLE:"DELETE_ROLE",
     UPDATE_ROLE:"UPDATE_ROLE",
     SEARCH_ROLE:"SEARCH_ROLE",
     LIST_ROLES: "LIST_ROLES", 
}